import type { MealItems } from "./types";

export const INITIAL_MEAL_ITEMS: MealItems = {
  Breakfast: [
    "Oatmeal with Berries",
    "Scrambled Eggs and Toast",
    "Greek Yogurt with Honey",
    "Avocado Toast",
    "Smoothie with Spinach and Banana",
    "Pancakes with Maple Syrup",
    "Cereal with Milk",
    "Breakfast Burrito",
    "Bagel with Cream Cheese",
    "Waffles with Strawberries",
    "Quiche Lorraine",
    "English Muffin with Jam",
    "Fruit Salad",
    "Cottage Cheese with Peaches",
  ],
  Lunch: [
    "Grilled Chicken Salad",
    "Turkey Sandwich on Whole Wheat",
    "Quinoa Bowl with Roasted Vegetables",
    "Lentil Soup",
    "Tuna Salad Wrap",
    "Caprese Salad",
    "Leftover Pasta",
    "Chicken Caesar Wrap",
    "BLT Sandwich",
    "Veggie Burger",
    "Sushi Rolls",
    "Greek Salad with Feta",
    "Tomato Soup and Grilled Cheese",
    "Spring Rolls",
  ],
  Dinner: [
    "Salmon with Asparagus",
    "Spaghetti Bolognese",
    "Chicken Stir-fry with Rice",
    "Beef Tacos",
    "Margherita Pizza",
    "Vegetable Curry",
    "Baked Ziti",
    "Roast Chicken with Potatoes",
    "Pork Chops with Applesauce",
    "Shrimp Scampi",
    "Fajitas with Peppers and Onions",
    "Lasagna",
    "Black Bean Burgers",
    "Shepherd's Pie",
  ],
  Snack: [
    "Apple with Peanut Butter",
    "Handful of Almonds",
    "String Cheese",
    "Carrots with Hummus",
    "Rice Cakes",
    "Hard-boiled Egg",
    "Popcorn",
    "Mixed Nuts",
    "Trail Mix",
    "Pretzels",
    "Grapes",
    "Dark Chocolate Square",
    "Orange",
    "Energy Bar",
  ],
};
