import type { MealItems } from "./types";

export const INITIAL_MEAL_ITEMS: MealItems = {
  Breakfast: [
    "Aloo Paratha",
    "Methi Paratha",
    "Paneer Paratha",
    "Sattu Paratha",
    "Poha",
    "Upma",
    "Idli with Sambar",
    "Dosa with Chutney",
    "Appam with Stew",
    "Rava Idli",
    "Pesarattu",
    "Rava Upma",
    "Moong Dal Chilla",
    "Besan Chilla",
    "Sprout Chilla",
    "Quinoa Upma",
    "Greek Yogurt",
    "Dhokla",
  ],
  Lunch: [
    "Dal Tadka with Roti",
    "Rajma with Rice",
    "Chana Masala",
    "Paneer Butter Masala",
    "Aloo Gobi",
    "Bhindi Masala",
    "Palak Paneer",
    "Sambar Rice",
    "Bisi Bele Bath",
    "Lemon Rice",
    "Curd Rice",
    "Rasam with Rice",
    "Brinjal Pepper Fry",
    "Vegetable Korma",
    "Vegetable Fried Rice",
    "Quinoa Khichdi",
    "Mixed Dal Khichdi",
    "Chickpea Salad",
    "Paneer Bhurji",
    "Spinach Paratha",
  ],
  Dinner: [
    "Moong Dal Khichdi",
    "Vegetable Fried Rice",
    "Masoor Dal",
    "Toor Dal with Rice",
    "Paneer Butter Masala",
    "Chickpea Curry",
    "Aloo Matar",
    "Mixed Vegetable Curry",
    "Idli with Sambar",
    "Upma with Vegetables",
    "Vegetable Stew",
    "Dal Makhani",
    "Chana Masala",
    "Palak Paneer",
    "Moong Dal",
  ],
  Snack: [
    "Roasted Chana",
    "Makhana",
    "Fruit Chaat",
    "Poha Chivda",
    "Bhel Puri",
    "Vegetable Frankie",
    "Moong Dal Vada",
    "Besan Chilla",
    "Oats Tikki",
    "Pakoras/Bhajji",
    "Dhokla",
    "Paneer Tikka",
    "Sprouted Moong Salad",
    "Sprout Salad",
  ],
};
